# Ore Finder plugin configuration file - config.yml

# The number of blocks in each direction that the Ore-Finder will operate on (number)
radius: 16

# Amount of time for which ores will be visible after using Ore-Finder (seconds)
cooldown: 10

# Should Ore-Finder crafting be enabled? (true/false)
enable-crafting: true